name: Syntax Check

on: push

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Check Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        # opam/install.sh is not our own script
        ignore_paths: opam
